### ISSUE TITLE
When shall we embark on this adventure?

### ISSUE THREAD

**Issue by alykat** [ctbarna/letsgettacos#1]
How do we pick dates en masse? A Doodle calendar or something? http://doodle.com

**Comment by ctbarna** [comment]
How about June 10th?

**Comment by alykat** [comment]
Thumbs-up from me. What sayeth other folks?

**Comment by chriszs** [comment]
+1

**Comment by ctbarna** [comment]
Actually, how about June 17th? The following wednesday.

**Comment by alykat** [comment]
Works for me.

**Comment by ctbarna** [comment]
Alright, let's do June 17th at 6:30.
