### ISSUE TITLE
Where shall we go?

### ISSUE THREAD

**Issue by alykat** [ctbarna/letsgettacos#2]
Places I've been that offer decent tacos:
- El Centro, D.F. (14th Street or Georgetown)
- District Taco (multiple locations)
- TaKorean (Union Market and Barracks Row)
- Oyamel (Penn Quarter)

And there's that gas station place I've heard is amazing, but I can't remember the name.

**Comment by ctbarna** [comment]
I'll also throw Tacos Impala (on H St) and El Rey (U St) in.

**Comment by ctbarna** [comment]
Judy Restaurant (on 14th), too.

**Comment by erikreyna** [comment]
Taqueria Habanero DC is a not so well known one that is pretty good, next to by Red Derby in Columbia Heights.

**Comment by ctbarna** [comment]
Let's do Judy Restaurant. Cheap, can handle random drop-in groups. Not too far off metro.
